name: nodejs-feature-branch-workflow

on :
  # This workflow is triggered when called by another workflow using the `workflow_call` event.
  workflow_call:
    inputs:
      project:
        description: 'Project'
        required: true
        type: string
      component:
        description: 'Component'
        required: true
        type: string
    secrets:
      DEPENDABOT_TOKEN:
        description: 'Token for Dependabot security checks'
        required: true


jobs:
  trigger-workflow:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Read version
        id: package_version
        run: |
          APP_VERSION=$(jq -r .version package.json)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Check app version
        run: echo "$APP_VERSION"

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        id: unit_tests
        run: npm test

      - name: Check dependabot alerts
        id: library_scan
        uses: Posture-Cybersecurity/dependabot-security-checker@v1.1.5
        with:
          github-token: ${{ secrets.DEPENDABOT_TOKEN }}
          severities: 'critical,high'  # Only check critical and high
          output-file: 'security-report.csv'
          fail-on-alerts: 'true'  # Fail workflow if alerts found

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
