name: nodejs-feature-branch-workflow

on :
  # This workflow is triggered when called by another workflow using the `workflow_call` event.
  workflow_call:
    inputs:
      project:
        description: 'Project'
        required: true
        type: string
      component:
        description: 'Component'
        required: true
        type: string
      environment:
        description: 'Environment'
        required: true
        type: string


jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: List files
        run: ls -la
